apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: globallimits.tekton.devops
spec:
  group: tekton.devops
  names:
    kind: GlobalLimit
    plural: globallimits
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                maxPipelines:
                  type: integer
