apiVersion: v1
kind: Secret
metadata:
  name: tekton-queue-cacerts
  namespace: tekton-pipelines
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    -----END RSA PRIVATE KEY-----
